name: educo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  equatable: ^2.0.5
  smooth_page_indicator: ^1.1.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/comments/
    - assets/images/courses/
    - assets/images/feedbacks/
    - assets/images/lessons/
    - assets/images/projects/
    - assets/images/teachers/
    - assets/images/navbar/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
